---
abstract: "Perl extension to OpenSSL's PKCS10 API."
author:
  - 'JoNO <jonozzz@yahoo.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-OpenSSL-PKCS10
no_index:
  directory:
    - t
    - inc
requires:
  Crypt::OpenSSL::RSA: 0
version: 0.15
